### PR TITLE
add awesome tailwind to community section

### PR DESCRIPTION
**Pull request by joshmanders**
This adds [Awesome Tailwind CSS](https://github.com/aniftyco/awesome-tailwindcss) to the community section so those coming to the docs/website can find more awesome stuff related to tailwind. 👍

### CODE REVIEW

**Comment by joshmanders** [comment]
Fixed, nice catch @hawezo.

**Comment by joshmanders** [comment]
bump @adamwathan

**Comment by adamwathan** [comment]
This is great, thanks guys!

**Comment by joshmanders** [comment]
Thanks Adam! Keep up the great work, we appreciate you.

**Pull request merged**
