### PR TITLE
Add dedicated search page and OpenSearch meta

### PR DESCRIPTION
**Pull request by rockhopper72**
This PR adds a dedicated search page located at `/docs/search` and implements [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) so that users can add custom search engines (tested in Chrome and Firefox).

This search page provides some of the benefits of a server-side rendered search (dedicated URL and search param) without straying from Algolia's Docsearch implementation.

**How to use**:
1. From your browser, visit `/docs/search?q=color`
1. See the search page and results for the query "color"

~~Note: the search results box will not close on the search page.~~

**TODO:**
- [x] The autocomplete suggestions will not go away if you navigate to a different page.
  - Fixed by making the autocomplete suggestions not locked open

**Further reading**: 
- [Adding a Custom search engine in Chrome](https://www.techrepublic.com/article/pro-tip-add-custom-search-engines-in-chrome-for-more-efficient-searching/)

### CODE REVIEW

**Comment by rockhopper72** [comment]
See it live on the [deploy preview](https://deploy-preview-107--elated-stonebraker-70896a.netlify.com/docs/search/?q=color)!

**Comment by rockhopper72** [comment]
Navigating to different pages doesn't work on the deploy preview because of cross-origin security.

**Comment by rockhopper72** [comment]
I'm not really sure which branch I should merge into, `master` or `next`? Thanks

**Comment by adamwathan** [comment]
Hey thanks for this! I don't know a ton about OpenSearch or the use cases, how does this work with custom search engines in Chrome/Firefox, like what does it let you do?

**Comment by rockhopper72** [comment]
Thanks for asking. Let's say I search the Tailwind Docs a lot (I do), and so instead of going to the tailwind site, clicking the search bar, and typing in my query, I can type "tw <query>" right into my browser's address bar and go straight to the search results.

**Comment by hacknug** [comment]
Would also allow use with DuckDuckGo's bang's https://duckduckgo.com/bang

**Pull request closed without merging**
