### PR TITLE
Add border-collapse utilities

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Added support for the `false` state variant
- Added support for the empty (`[]`) state variant
- Added `border-collapse` utilities

### CODE REVIEW

**Comment by adamwathan** [comment]
Great thanks @MichaelDeBoey! Do you mind updating the PR to put this page in a new section called "Tables"? I think that will make it easier for people to find and will also help this section show up in the docs search when someone types "table".

I'm going to add utilities for `table-layout: fixed/auto` in the next patch release too so those will go under the "Tables" category as well.

**Comment by MichaelDeBoey** [comment]
@adamwathan Done 🙂

**Comment by MichaelDeBoey** [comment]
@adamwathan Couldn't test the docs locally (due to #16), so had to check the Netlify build each time, but I think it's OK right now 🙂

**Comment by adamwathan** [comment]
Is Netlify automatically running builds for PRs? That's awesome if so, I tried to migrate the site there a while ago but their SSL stuff didn't work properly and took the whole site down so had to migrate back to self-hosted. Would like to try it again some time.

**Comment by MichaelDeBoey** [comment]
@adamwathan If you `Show all checks` and press the Netlify `details`, you go to the deployed version of this PR
Navigating the site via the menu isn't possible for me, but I just  change the URL instead 🙂

**Pull request merged**
