### PR TITLE
Add docs for user select utilities

### PR DESCRIPTION
**Pull request by swanson**
Document usage for `select-text` and `select-none`

Preview: https://deploy-preview-191--elated-stonebraker-70896a.netlify.com/docs/user-select

### CODE REVIEW

**Comment by adamwathan** [comment]
This is awesome, thanks so much @swanson! I actually added new user-select utilities recently that never made it into the docs:

https://github.com/tailwindcss/tailwindcss/pull/885

Do you feel like adding those as well? If not I will merge this as-is and add the remaining examples myself over the next few days 👍 Thanks again, really really appreciate PRs like this!

**Comment by swanson** [comment]
I'll add them to this PR and remove the customizing additions.

**Comment by swanson** [comment]
@adamwathan `user-select: contain` isn't supported in Chrome/Safari/Firefox: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#Browser_compatibility -- maybe that one should remain undocumented? Might be confusing to have an example and require you to open IE/Edge to see any difference.

**Comment by adamwathan** [comment]
Ah good catch, I think I'll just remove that altogether.

**Comment by swanson** [comment]
Sounds good, this PR should be ready to merge then: it documents "auto", "none", "text", "all"

**Pull request merged**
